import Head from "next/head";
import { useEffect } from "react";
import { SpeedTable } from "@/models/table/table";
import { SpeedPage } from "@/components/page/SpeedPage";
import { useSpeedState } from "@/hooks/games/speed/useSpeedState";

export default function Speed() {
  const {
    speedTable,
    handleClickCard,
    cardsInStrages,
    handleClickCardInStrages,
    hancleClickGameStartBtn,
    hancleClickGameReStartBtn,
    executeHouseAction,
  } = useSpeedState("username");

  const SpeedPageProps = {
    speedTable,
    handleClickCard,
    cardsInStrages,
    handleClickCardInStrages,
    hancleClickGameStartBtn,
    hancleClickGameReStartBtn,
    executeHouseAction,
  };
  return (
    <>
      <Head>
        <title>Speed</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <SpeedPage {...SpeedPageProps} />
      </div>
    </>
  );
}
