import Head from "next/head";
import React from "react";
import { BlackjackPage } from "@/components/page/BlackjackPage";

export default function Blackjack() {
  return (
    <>
      <Head>
        <title>Blackjack</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BlackjackPage />
    </>
  );
}
