import Head from "next/head";

export default function TexasHoldemPoker() {
  return (
    <>
      <Head>
        <title>Texas Holdem Poker</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <p>Texas hold</p>
      </div>
    </>
  );
}
