import { CardComponent } from "@/components/model/card/CardComponent";
import { HomePage } from "@/components/page/HomePage";
import { Card } from "@/models/card/card";
// import { BasicButton } from "@/components/ui/atoms/buttons/BasicButton";
import Head from "next/head";
import React from "react";

export default function Home() {
  const c = new Card("A", "H", true, "/cards/A-H.png");
  return (
    <>
      <Head>
        <title>Card Game App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <HomePage />
      </div>
    </>
  );
}
