import { HomePage } from "@/components/page/HomePage";
import { BasicButton } from "@/components/commonUI/atoms/buttons/BasicButton";
import Head from "next/head";
import React from "react";

export default function Home() {
  return (
    <>
      <Head>
        <title>Card Game App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <HomePage />
      </div>
    </>
  );
}
